name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: push action
        id: bucket
        uses: textileio/github-action-buckets@master
        with:
          key: ${{ secrets.TEXTILE_ACCOUNT_KEY }}
          secret: ${{ secrets.TEXTILE_ACCOUNT_SECRET }}
          bucket: 'bafzbeibowrp2jxzxuvh6k36pnm6qx4qdtidg5s6mgwqhqrjmlv2zabzopi'
          thread: 'bafk4zl3wjybcxdqxng2fqjkmvlo6trsd3ryfmmidl6iybitplqwtygy'
          path: ./public
      - name: Get the output CID
        run: echo "The CID was ${{ steps.push.outputs.cid }}"

      - name: Update DNSLink
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          RECORD_DOMAIN: 'ipfs.gauthier.uk'
          RECORD_NAME: '_dnslink.uk'
        id: dnslink
        uses: textileio/cloudflare-update-dnslink@master
        with:
          cid: ${{ steps.push.outputs.cid }}

      - name: Deploy GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
