name: ipfs deploy

on:
  push:
    branches:
      - gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: aquiladev/ipfs-action@v1
        with:
          path: ./
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
